# Configuration file for data extraction from ROOT files
# This file defines what data to extract and how to save it

# ---------------------------------

geometry: "HyperK" # wcte corresponds mathieu's ntuple format, HyperK to mine
input_file: "/sps/t2k/eleblevec/Datasets/custom_dataset/e-/200-1000MeV/WCTE_center_iso_1Mevents/test_1_a50/merged_e-_200-1000MeV.root"
output_file: "/sps/t2k/eleblevec/Datasets/custom_dataset/e-/200-1000MeV/WCTE_center_iso_1Mevents/test_1_a50/h5_data/e-_200-1000MeV.h5"
# ROOT file settings
tree_name: "pure_root_tree"

# All available variables to extract
# by default n_digi_hits, kinetic_energy, pid, vertex, towall, dwall, trigger_time are extracted
scalar_fields_config:
  - "pmt_charge"
  - "pmt_time"
  - "hitx"
  - "hity"
  - "hitz"  
  
vector_fields_config:
  vertex: ["vertex_x", "vertex_y", "vertex_z"]
  particle_dir: ["particle_dir_x", "particle_dir_y", "particle_dir_z"]
  particle_stop: ["particle_stop_x", "particle_stop_y", "particle_stop_z"]
  particle_start: ["particle_start_x", "particle_start_y", "particle_start_z"]
  
  # Add more vector fields as needed
  # momentum: ["momentum_x", "momentum_y", "momentum_z"]

# HDF5 settings
storage_mode: "hierarchical"
compression: "gzip"

# Monitoring settings
monitor_ram: false
monitor_interval: 500  # Check RAM every N events