# Configuration file for data extraction from ROOT files
# This file defines what data to extract and how to save it

# ---------------------------------
tree_name: "pure_root_tree"

# input_file: "/sps/t2k/eleblevec/Datasets/custom_dataset/e-/50-1500MeV/Ndigit_40_1Mevents/test_1_a1000/merged_e-_50-1500MeV.root"
geometry: "HyperK"
# input_file: "/sps/t2k/eleblevec/Datasets/custom_dataset/e-/50-1500MeV/Ndigit_40_1Mevents/train_val_21_a30/merged_e-_50-1500MeV.root"
input_file: "/sps/t2k/eleblevec/Datasets/custom_dataset/e-/50-1500MeV/Ndigit_40_1Mevents/test_1_a1000/merged_e-_50-1500MeV.root"
# output_file: "/sps/t2k/eleblevec/Datasets/custom_dataset/e-/50-1500MeV/Ndigit_40_1Mevents/train_val_21_a30/h5_data/e-_50-1500MeV_folder20_a30_with_tube_ids.h5"
output_file: "/sps/t2k/eleblevec/mini-Caverns-toolsbox/playground/ntupleManager/iterator_profiling.h5"

# fields to extract from the root file
field_config:
  - "n_digi_hits"
  - "energy"
  - "event_type"
  - "towall"
  - "dwall"
  - "trigger_time"
  - "vertex"
  - "particle_dir"
  - "particle_stop"
  - "particle_start"
  - "pmt_charge"
  - "pmt_time"
  - "tube_ids"

# Uproot settings
uproot_step_size: "20000" #event or 1GB, 500MB

# HDF5 settings
storage_mode: "hierarchical"
compression: "gzip"

# Monitoring settings
monitor_ram: true
monitor_interval: 1000  # Check RAM every N events